### ISSUE TITLE
crash in btree-psi after scm_unprotect_object called on unprotected object

### ISSUE THREAD

**Issue by yantrabuddhi** [opencog/ros-behavior-scripting#105]
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `guile -l btree-psi.scm'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007effd8efec37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007effd8efec37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007effd8f02028 in __GI_abort () at abort.c:89
#2  0x00007effd951d66a in scm_gc_unprotect_object () from /usr/lib/libguile-2.0.so.22
#3  0x00007effd708df4f in opencog::SchemeEval::do_eval (this=0x7efe500023c0, expr=...)
    at /home/hr/hansonrobotics/opencog/atomspace/opencog/guile/SchemeEval.cc:649
#4  0x00007effd708e0a3 in opencog::SchemeEval::c_wrap_eval (p=0x7efe500023c0)
    at /home/hr/hansonrobotics/opencog/atomspace/opencog/guile/SchemeEval.cc:583
#5  0x00007effd95062ca in ?? () from /usr/lib/libguile-2.0.so.22
#6  0x00007effd958d12a in ?? () from /usr/lib/libguile-2.0.so.22
#7  0x00007effd950f863 in scm_call_4 () from /usr/lib/libguile-2.0.so.22
#8  0x00007effd95069ff in ?? () from /usr/lib/libguile-2.0.so.22
#9  0x00007effd9506a95 in scm_c_with_continuation_barrier () from /usr/lib/libguile-2.0.so.22
#10 0x00007effd8c7a950 in GC_call_with_gc_active () from /usr/lib/x86_64-linux-gnu/libgc.so.1
#11 0x00007effd957f7d1 in ?? () from /usr/lib/libguile-2.0.so.22
#12 0x00007effd8c74fe2 in GC_call_with_stack_base () from /usr/lib/x86_64-linux-gnu/libgc.so.1
#13 0x00007effd957fb48 in scm_with_guile () from /usr/lib/libguile-2.0.so.22
#14 0x00007effd708e04e in opencog::SchemeEval::eval_expr (this=0x7efe500023c0, expr=...)
    at /home/hr/hansonrobotics/opencog/atomspace/opencog/guile/SchemeEval.cc:551
#15 0x00007effd6300a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007effd9295184 in start_thread (arg=0x7effb6045700) at pthread_create.c:312
#17 0x00007effd8fc237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

(gdb) frame 3
#3  0x00007effd708df4f in opencog::SchemeEval::do_eval (this=0x7efe500023c0, expr=...)
    at /home/hr/hansonrobotics/opencog/atomspace/opencog/guile/SchemeEval.cc:649
649     scm_gc_unprotect_object(_rc);
(gdb) print expr
$1 = (const std::string &) @0x7efe7c0ca470: <incomplete type>
(gdb) print (char*)0x7efe7c0ca470
$2 = 0x7efe7c0ca470 "H\331\006|\376~"
(gdb) print *(char**)0x7efe7c0ca470
$3 = 0x7efe7c06d948 "\n"

```

**Comment by linas** [comment]
You need to provide instructions about how to reproduce this.
